# fly.toml app configuration file generated for imgur-portal on 2024-03-07T17:06:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'imgur-portal'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5858
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
